### ISSUE TITLE
Duo 1.0.0 Roadmap

### ISSUE THREAD

**Issue by matthewmueller** [duojs/duo#143]
Had a chance to gather your guys feedback (thank you!) and think about this some more. I'd like to release by the end of next week. Here are the things that I think we need before we release. I would appreciate any and all help resolving these tasks. Also feel free to bring your own issues to the table for things you think should get resolved before release.
## Must Haves:
- [x] Remove the ability to do multiple builds at once in duo. No more `$ duo`

This was something I was gunning for, but after getting feedback from @yields and @stephenmathieson, I think my approach was ill-conceived. When you're working with a big app, you'll probably just want to integrate with `make` or `gulp` or `grunt`. 

A half-baked `main: [ ... ]` that builds a bunch of instances of Duo adds some nicety for simple projects like one with an `index.js` and `index.css`, but I think it complicates a lot of other issues.

I think keeping Duo to one file will give us more consistency on `stdio` and the CLI API. 
- [x] Add `stdin` for along with explicit type casting `-t` and `--type` for the entry.

Knowing the entry type is important for plugins, but if you pipe into stdin, you only get the source. To resolve this @yields suggested:

```
$ duo -t js < cat entry.js > out.js
```

I think this will work nicely. This also has the added benefit of allowing us to support `component.json` files as entries
- [x] Integrate watch as `duo -w entry.js` using [duo-watch](http://github.com/component/duo-watch).

This is a low overhead solution that reduces a lot of boilerplate. I think some people will scream feature creep, but most people will enjoy a well-tested integrated solution that speeds up their front-end development.
- [x] Add a quiet command `-q` to duo to suppress non-errors on `stderr`. 

Since we're using `stderr` for all logging, there should be a way to only report errors on the channel.
- [x] duo-gulp plugin

Open duo up to thousands of other plugins without much work

API will probably look like this, just because of how gulp works:

``` js
var gulp = require('duo-gulp');
var csso = require('gulp-csso');
duo.use(gulp(csso)(opts));
```
- [x] update readme 

Need to change the "Building Web Applications" section and write about stdin.
- [x] Multiple entries

As discussed here: https://github.com/component/duo/issues/177
- [x] Fix CSS @import's 

As reported here: https://github.com/component/duo/issues/181
## Nice to haves:

These are things that I probably won't work on, but if someone else wants to own, I'd love to include with the release.
- [x] A Duo website

Would be really cool to show off Duo using Duo. I think we could add search and a lot of cool features once we have a website. I will probably get around to doing it at some point, but I just don't have the bandwidth right now to work on it. If anyone is interested in working on the website, I can loop you into the initial discussions.
- [ ] Bitbucket support

This is a project @stephenmathieson is passionate about. I'd love to make Duo work with other providers and I think we will have to at some point. I think if we could squeeze this in to the launch that would be great, but I don't want to prolong the release or destabilize the project.
## 

That's all for now. Let me know what you guys think. Sorry if I'm including you and you weren't interested :-P

/cc @yields @ianstormtaylor @juliangruber @lancejpollard @anthonyshort @dominicbarnes @stephenmathieson
