### ISSUE TITLE
v1?

### ISSUE THREAD

**Issue by yields** [duojs/duo#395]
Any thoughts on what we need to get to v1? i think if we come up with a todo list or something, it will speed up development on v1...

cc @MatthewMueller @stephenmathieson

**Comment by johntron** [comment]
Here's an update:
- [x] #76 Pinning: https://github.com/stephenmathieson/duo-pin
- [x] Searching (still no registry #197) - https://github.com/johntron/duo-search
- [ ] #125 Sourcemaps - Just need a version bump
- [ ] #355 and #103 Log missing assets
- [ ] #96 `duo-install(1)`
- [ ] #378 Easily update dependencies
- [ ] #283 More sourcemaps
- [ ] #386 Caching
- [ ] #291 Hooks
- [ ] #362 `duo --use`
- [ ] #396 Concord metadata standard?
- [ ] #346 Build plugins after build, before writing
- [ ] #220 Deterministic Builds
